In [ ]:
# CMP7005 Programming for Data Analysis
## PRAC1 – From Data to Application Development

### Task 1: Data Handling
#### Importing and analyzing datasets, merging both datasets by identifying the primary key

In [1]:
# Importing pandas and numpy libraries , dispaly all columns
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [2]:
# Load the loan approval dataset
dataset1 = pd.read_csv("../data/Loan_Approval_Data_Set_1.csv")
dataset2 = pd.read_csv("../data/Loan_Approval_Data_Set_2.csv")

In [3]:
# Display thr numbers of rows and columns
print("Dataset 1 shape:", dataset1.shape)
print("Dataset 2 shape:", dataset2.shape)

Dataset 1 shape: (20000, 16)
Dataset 2 shape: (20000, 18)

In [4]:
# Print column names
print("Dataset 1 columns:")
print(dataset1.columns.tolist())

print("\nDataset 2 columns:")
print(dataset2.columns.tolist())

Dataset 1 columns:
['ID', 'ApplicationDate', 'AnnualIncome', 'EmploymentStatus', 'Experience', 'LoanDuration', 'NumberOfDependents', 'MonthlyDebtPayments', 'NumberOfOpenCreditLines', 'BankruptcyHistory', 'PreviousLoanDefaults', 'LengthOfCreditHistory', 'CheckingAccountBalance', 'TotalLiabilities', 'NetWorth', 'LoanApproved']

Dataset 2 columns:
['ApplicationDate', 'Age', 'CreditScore', 'EducationLevel', 'Experience', 'LoanAmount', 'MaritalStatus', 'HomeOwnershipStatus', 'ID', 'CreditCardUtilizationRate', 'NumberOfCreditInquiries', 'LoanPurpose', 'PaymentHistory', 'SavingsAccountBalance', 'TotalAssets', 'JobTenure', 'InterestRate', 'RiskScore']

In [5]:
# Summary of dataset
dataset1.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       20000 non-null  str
 1   ApplicationDate          20000 non-null  str
 2   AnnualIncome             20000 non-null  int64
 3   EmploymentStatus         20000 non-null  str
 4   Experience               20000 non-null  int64
 5   LoanDuration             20000 non-null  int64
 6   NumberOfDependents       20000 non-null  int64
 7   MonthlyDebtPayments      20000 non-null  int64
 8   NumberOfOpenCreditLines  20000 non-null  int64
 9   BankruptcyHistory        20000 non-null  int64
 10  PreviousLoanDefaults     20000 non-null  int64
 11  LengthOfCreditHistory    20000 non-null  int64
 12  CheckingAccountBalance   20000 non-null  int64
 13  TotalLiabilities         20000 non-null  int64
 14  NetWorth                 20000 non-null  int64
 15  LoanApproved             20000 non-null  int64
dtypes: int64(13), str(3)
memory usage: 2.4 MB

In [6]:
dataset2.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ApplicationDate            20000 non-null  str
 1   Age                        20000 non-null  int64
 2   CreditScore                20000 non-null  int64
 3   EducationLevel             20000 non-null  str
 4   Experience                 19334 non-null  float64
 5   LoanAmount                 20000 non-null  int64
 6   MaritalStatus              19985 non-null  str
 7   HomeOwnershipStatus        20000 non-null  str
 8   ID                         20000 non-null  str
 9   CreditCardUtilizationRate  20000 non-null  float64
 10  NumberOfCreditInquiries    20000 non-null  int64
 11  LoanPurpose                20000 non-null  str
 12  PaymentHistory             20000 non-null  int64
 13  SavingsAccountBalance      20000 non-null  int64
 14  TotalAssets                20000 non-null  int64
 15  JobTenure                  20000 non-null  int64
 16  InterestRate               20000 non-null  float64
 17  RiskScore                  20000 non-null  str
dtypes: float64(3), int64(8), str(7)
memory usage: 2.7 MB

In [7]:
#Analyze row counts and verify uniqueness of the ID column
print("Dataset 1")
print("Rows:", len(dataset1))
print("Unique IDs:", dataset1["ID"].nunique())
print("Duplicate IDs:", dataset1["ID"].duplicated().sum())

print("\nDataset 2")
print("Rows:", len(dataset2))
print("Unique IDs:", dataset2["ID"].nunique())
print("Duplicate IDs:", dataset2["ID"].duplicated().sum())

Dataset 1
Rows: 20000
Unique IDs: 20000
Duplicate IDs: 0

Dataset 2
Rows: 20000
Unique IDs: 20000
Duplicate IDs: 0

In [8]:
#Check unique Id in both datasets are identical
ids_match = set(dataset1["ID"]) == set(dataset2["ID"])

print("Do both datasets contain the same IDs?", ids_match)

Do both datasets contain the same IDs? True

In [ ]:
# Merging the Datasets
### ID was chosen as the primary key to merge the datasets because it uniquely identifies records from each dataset

In [9]:
# Identifying overlapping columns
common_columns = set(dataset1.columns).intersection(set(dataset2.columns))

print("Common columns:")
print(common_columns)

Common columns:
{'ID', 'Experience', 'ApplicationDate'}

In [10]:
# Compare the number of unique entries for shared columns except ID
for col in common_columns:
    if col != "ID":
        print(f"\nColumn: {col}")
        print("Dataset 1 unique values:", dataset1[col].nunique(dropna=False))
        print("Dataset 2 unique values:", dataset2[col].nunique(dropna=False))

Column: Experience
Dataset 1 unique values: 62
Dataset 2 unique values: 62

Column: ApplicationDate
Dataset 1 unique values: 2922
Dataset 2 unique values: 20000

In [11]:
# Inner join datasets using ID
merged_df = pd.merge(
    dataset1,
    dataset2,
    on="ID",
    how="inner",
    suffixes=("_ds1", "_ds2")
)

In [12]:
# Check first few rows of the merged dataset
print("Merged dataset shape:", merged_df.shape)
merged_df.head()

Merged dataset shape: (20000, 33)

,ID,ApplicationDate_ds1,AnnualIncome,EmploymentStatus,Experience_ds1,LoanDuration,NumberOfDependents,MonthlyDebtPayments,NumberOfOpenCreditLines,BankruptcyHistory,PreviousLoanDefaults,LengthOfCreditHistory,CheckingAccountBalance,TotalLiabilities,NetWorth,LoanApproved,ApplicationDate_ds2,Age,CreditScore,EducationLevel,Experience_ds2,LoanAmount,MaritalStatus,HomeOwnershipStatus,CreditCardUtilizationRate,NumberOfCreditInquiries,LoanPurpose,PaymentHistory,SavingsAccountBalance,TotalAssets,JobTenure,InterestRate,RiskScore
0,A001,01-01-2018,39948,Employed,22,48,2,183,1,0,0,9,1202,19183,126928,0,01-01-2018,45,617,Master,22.0,13152,Married,Own,35.40,2,Home,29,7632,146111,11,22.75,49
1,A002,02-01-2018,39709,Employed,15,48,1,496,5,0,0,9,3460,9595,43609,0,02-01-2018,38,628,Associate,NaN,26045,Single,Mortgage,8.78,3,Debt Consolidation,21,4627,53204,3,20.10,XX
2,A003,03-01-2018,40724,Employed,26,36,2,902,2,0,0,22,895,128874,5205,0,03-01-2018,47,570,Bachelor,26.0,17627,Married,Rent,13.70,0,Education,20,886,25176,6,21.25,XX
3,A004,04-01-2018,69084,Employed,34,96,1,755,2,0,0,10,1217,5370,99452,0,04-01-2018,58,545,High School,34.0,37898,Single,Mortgage,2.67,1,Home,27,1675,104822,5,30.09,54
4,A005,05-01-2018,103264,Employed,17,36,1,274,0,0,0,27,4981,17286,227019,1,05-01-2018,37,594,Associate,17.0,9184,Married,Mortgage,3.20,0,Debt Consolidation,26,1555,244305,5,17.59,36

In [13]:
# Check row counts and ID uniqueness before and after combining the data
print("Rows in Dataset 1:", len(dataset1))
print("Rows in Dataset 2:", len(dataset2))
print("Rows after merge:", len(merged_df))

print("\nDuplicate IDs after merge:")
print(merged_df["ID"].duplicated().sum())

print("\nUnique IDs after merge:")
print(merged_df["ID"].nunique())

Rows in Dataset 1: 20000
Rows in Dataset 2: 20000
Rows after merge: 20000

Duplicate IDs after merge:
0

Unique IDs after merge:
20000

In [14]:
# Validate that the merged data has exactly 20000 rows
assert len(merged_df) == 20000
assert merged_df["ID"].nunique() == 20000
assert merged_df["ID"].duplicated().sum() == 0

print("Merge validation successful.")

Merge validation successful.

In [15]:
# Print the list of column names in the dataset
print(merged_df.columns.tolist())

['ID', 'ApplicationDate_ds1', 'AnnualIncome', 'EmploymentStatus', 'Experience_ds1', 'LoanDuration', 'NumberOfDependents', 'MonthlyDebtPayments', 'NumberOfOpenCreditLines', 'BankruptcyHistory', 'PreviousLoanDefaults', 'LengthOfCreditHistory', 'CheckingAccountBalance', 'TotalLiabilities', 'NetWorth', 'LoanApproved', 'ApplicationDate_ds2', 'Age', 'CreditScore', 'EducationLevel', 'Experience_ds2', 'LoanAmount', 'MaritalStatus', 'HomeOwnershipStatus', 'CreditCardUtilizationRate', 'NumberOfCreditInquiries', 'LoanPurpose', 'PaymentHistory', 'SavingsAccountBalance', 'TotalAssets', 'JobTenure', 'InterestRate', 'RiskScore']

In [16]:
# Save the merged dataset
merged_df.to_csv("../data/Loan_Approval_Merged.csv", index=False)

print("Merged dataset saved successfully.")

Merged dataset saved successfully.

In [17]:
# Verify the saved file
merged_check = pd.read_csv("../data/Loan_Approval_Merged.csv")

print("Saved dataset shape:", merged_check.shape)
merged_check.head()

Saved dataset shape: (20000, 33)

,ID,ApplicationDate_ds1,AnnualIncome,EmploymentStatus,Experience_ds1,LoanDuration,NumberOfDependents,MonthlyDebtPayments,NumberOfOpenCreditLines,BankruptcyHistory,PreviousLoanDefaults,LengthOfCreditHistory,CheckingAccountBalance,TotalLiabilities,NetWorth,LoanApproved,ApplicationDate_ds2,Age,CreditScore,EducationLevel,Experience_ds2,LoanAmount,MaritalStatus,HomeOwnershipStatus,CreditCardUtilizationRate,NumberOfCreditInquiries,LoanPurpose,PaymentHistory,SavingsAccountBalance,TotalAssets,JobTenure,InterestRate,RiskScore
0,A001,01-01-2018,39948,Employed,22,48,2,183,1,0,0,9,1202,19183,126928,0,01-01-2018,45,617,Master,22.0,13152,Married,Own,35.40,2,Home,29,7632,146111,11,22.75,49
1,A002,02-01-2018,39709,Employed,15,48,1,496,5,0,0,9,3460,9595,43609,0,02-01-2018,38,628,Associate,NaN,26045,Single,Mortgage,8.78,3,Debt Consolidation,21,4627,53204,3,20.10,XX
2,A003,03-01-2018,40724,Employed,26,36,2,902,2,0,0,22,895,128874,5205,0,03-01-2018,47,570,Bachelor,26.0,17627,Married,Rent,13.70,0,Education,20,886,25176,6,21.25,XX
3,A004,04-01-2018,69084,Employed,34,96,1,755,2,0,0,10,1217,5370,99452,0,04-01-2018,58,545,High School,34.0,37898,Single,Mortgage,2.67,1,Home,27,1675,104822,5,30.09,54
4,A005,05-01-2018,103264,Employed,17,36,1,274,0,0,0,27,4981,17286,227019,1,05-01-2018,37,594,Associate,17.0,9184,Married,Mortgage,3.20,0,Debt Consolidation,26,1555,244305,5,17.59,36

In [ ]:
## Task 2: Exploratory Data Analysis (EDA)

### 2.1 Fundamental Data Understanding

### Examines the structure, characteristics, data types, unique values, distributions, and missing values within the merged dataset

In [18]:
merged_df = pd.read_csv("../data/Loan_Approval_Merged.csv")

print("Dataset loaded successfully.")
print("Dataset shape:", merged_df.shape)

Dataset loaded successfully.
Dataset shape: (20000, 33)

In [19]:
rows, columns = merged_df.shape

print("Number of rows:", rows)
print("Number of columns:", columns)

Number of rows: 20000
Number of columns: 33

In [20]:
merged_df.head()

,ID,ApplicationDate_ds1,AnnualIncome,EmploymentStatus,Experience_ds1,LoanDuration,NumberOfDependents,MonthlyDebtPayments,NumberOfOpenCreditLines,BankruptcyHistory,PreviousLoanDefaults,LengthOfCreditHistory,CheckingAccountBalance,TotalLiabilities,NetWorth,LoanApproved,ApplicationDate_ds2,Age,CreditScore,EducationLevel,Experience_ds2,LoanAmount,MaritalStatus,HomeOwnershipStatus,CreditCardUtilizationRate,NumberOfCreditInquiries,LoanPurpose,PaymentHistory,SavingsAccountBalance,TotalAssets,JobTenure,InterestRate,RiskScore
0,A001,01-01-2018,39948,Employed,22,48,2,183,1,0,0,9,1202,19183,126928,0,01-01-2018,45,617,Master,22.0,13152,Married,Own,35.40,2,Home,29,7632,146111,11,22.75,49
1,A002,02-01-2018,39709,Employed,15,48,1,496,5,0,0,9,3460,9595,43609,0,02-01-2018,38,628,Associate,NaN,26045,Single,Mortgage,8.78,3,Debt Consolidation,21,4627,53204,3,20.10,XX
2,A003,03-01-2018,40724,Employed,26,36,2,902,2,0,0,22,895,128874,5205,0,03-01-2018,47,570,Bachelor,26.0,17627,Married,Rent,13.70,0,Education,20,886,25176,6,21.25,XX
3,A004,04-01-2018,69084,Employed,34,96,1,755,2,0,0,10,1217,5370,99452,0,04-01-2018,58,545,High School,34.0,37898,Single,Mortgage,2.67,1,Home,27,1675,104822,5,30.09,54
4,A005,05-01-2018,103264,Employed,17,36,1,274,0,0,0,27,4981,17286,227019,1,05-01-2018,37,594,Associate,17.0,9184,Married,Mortgage,3.20,0,Debt Consolidation,26,1555,244305,5,17.59,36

In [21]:
merged_df.sample(5, random_state=42)

,ID,ApplicationDate_ds1,AnnualIncome,EmploymentStatus,Experience_ds1,LoanDuration,NumberOfDependents,MonthlyDebtPayments,NumberOfOpenCreditLines,BankruptcyHistory,PreviousLoanDefaults,LengthOfCreditHistory,CheckingAccountBalance,TotalLiabilities,NetWorth,LoanApproved,ApplicationDate_ds2,Age,CreditScore,EducationLevel,Experience_ds2,LoanAmount,MaritalStatus,HomeOwnershipStatus,CreditCardUtilizationRate,NumberOfCreditInquiries,LoanPurpose,PaymentHistory,SavingsAccountBalance,TotalAssets,JobTenure,InterestRate,RiskScore
10650,B652,28-02-2023,100761,Employed,16,84,0,88,3,0,0,19,1421,2909,7304,1,28-02-2047,37,604,High School,16.0,28479,Single,Mortgage,28.00,1,Debt Consolidation,23,2254,10213,7,22.23,41
2041,A2042,04-08-2023,189154,Employed,11,60,2,411,2,0,0,12,3706,20156,22443,1,04-08-2023,35,509,High School,11.0,11222,Married,Mortgage,2.89,4,Debt Consolidation,30,4456,42599,7,27.04,38
8668,A8669,25-09-2025,73272,Employed,20,48,0,442,4,0,0,25,1619,55131,20044,0,25-09-2041,44,483,High School,20.0,31573,Widowed,Own,5.13,1,Home,21,5212,75175,1,34.20,53
1114,A1115,19-01-2021,57115,Employed,20,12,3,409,1,0,0,14,1389,40497,1714,0,19-01-2021,41,412,Master,20.0,21937,Married,Rent,2.56,1,Debt Consolidation,23,5046,6435,5,28.06,50
13902,B3904,24-01-2024,61155,Employed,19,48,0,533,6,0,0,3,2117,16756,55941,0,24-01-2056,39,551,Master,19.0,31510,Divorced,Rent,2.16,1,Debt Consolidation,19,9010,72697,3,25.08,51

In [22]:
merged_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 33 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         20000 non-null  str
 1   ApplicationDate_ds1        20000 non-null  str
 2   AnnualIncome               20000 non-null  int64
 3   EmploymentStatus           20000 non-null  str
 4   Experience_ds1             20000 non-null  int64
 5   LoanDuration               20000 non-null  int64
 6   NumberOfDependents         20000 non-null  int64
 7   MonthlyDebtPayments        20000 non-null  int64
 8   NumberOfOpenCreditLines    20000 non-null  int64
 9   BankruptcyHistory          20000 non-null  int64
 10  PreviousLoanDefaults       20000 non-null  int64
 11  LengthOfCreditHistory      20000 non-null  int64
 12  CheckingAccountBalance     20000 non-null  int64
 13  TotalLiabilities           20000 non-null  int64
 14  NetWorth                   20000 non-null  int64
 15  LoanApproved               20000 non-null  int64
 16  ApplicationDate_ds2        20000 non-null  str
 17  Age                        20000 non-null  int64
 18  CreditScore                20000 non-null  int64
 19  EducationLevel             20000 non-null  str
 20  Experience_ds2             19334 non-null  float64
 21  LoanAmount                 20000 non-null  int64
 22  MaritalStatus              19985 non-null  str
 23  HomeOwnershipStatus        20000 non-null  str
 24  CreditCardUtilizationRate  20000 non-null  float64
 25  NumberOfCreditInquiries    20000 non-null  int64
 26  LoanPurpose                20000 non-null  str
 27  PaymentHistory             20000 non-null  int64
 28  SavingsAccountBalance      20000 non-null  int64
 29  TotalAssets                20000 non-null  int64
 30  JobTenure                  20000 non-null  int64
 31  InterestRate               20000 non-null  float64
 32  RiskScore                  20000 non-null  str
dtypes: float64(3), int64(21), str(9)
memory usage: 5.0 MB

In [23]:
data_types = pd.DataFrame({
    "Column": merged_df.columns,
    "Data Type": merged_df.dtypes.astype(str).values
})

data_types

                       Column Data Type
0                          ID       str
1         ApplicationDate_ds1       str
2                AnnualIncome     int64
3            EmploymentStatus       str
4              Experience_ds1     int64
5                LoanDuration     int64
6          NumberOfDependents     int64
7         MonthlyDebtPayments     int64
8     NumberOfOpenCreditLines     int64
9           BankruptcyHistory     int64
10       PreviousLoanDefaults     int64
11      LengthOfCreditHistory     int64
12     CheckingAccountBalance     int64
13           TotalLiabilities     int64
14                   NetWorth     int64
15               LoanApproved     int64
16        ApplicationDate_ds2       str
17                        Age     int64
18                CreditScore     int64
19             EducationLevel       str
20             Experience_ds2   float64
21                 LoanAmount     int64
22              MaritalStatus       str
23        HomeOwnershipStatus       str
24  CreditCardUtilizationRate   float64
25    NumberOfCreditInquiries     int64
26                LoanPurpose       str
27             PaymentHistory     int64
28      SavingsAccountBalance     int64
29                TotalAssets     int64
30                  JobTenure     int64
31               InterestRate   float64
32                  RiskScore       str

In [25]:
numerical_columns = merged_df.select_dtypes(include=np.number).columns.tolist()
categorical_columns = merged_df.select_dtypes(
    include=["object", "str", "category"]
).columns.tolist()

print("Number of numerical columns:", len(numerical_columns))
print("Number of categorical columns:", len(categorical_columns))

print("\nNumerical columns:")
print(numerical_columns)

print("\nCategorical columns:")
print(categorical_columns)

Number of numerical columns: 24
Number of categorical columns: 9

Numerical columns:
['AnnualIncome', 'Experience_ds1', 'LoanDuration', 'NumberOfDependents', 'MonthlyDebtPayments', 'NumberOfOpenCreditLines', 'BankruptcyHistory', 'PreviousLoanDefaults', 'LengthOfCreditHistory', 'CheckingAccountBalance', 'TotalLiabilities', 'NetWorth', 'LoanApproved', 'Age', 'CreditScore', 'Experience_ds2', 'LoanAmount', 'CreditCardUtilizationRate', 'NumberOfCreditInquiries', 'PaymentHistory', 'SavingsAccountBalance', 'TotalAssets', 'JobTenure', 'InterestRate']

Categorical columns:
['ID', 'ApplicationDate_ds1', 'EmploymentStatus', 'ApplicationDate_ds2', 'EducationLevel', 'MaritalStatus', 'HomeOwnershipStatus', 'LoanPurpose', 'RiskScore']

In [26]:
unique_summary = pd.DataFrame({
    "Column": merged_df.columns,
    "Unique Values": [merged_df[col].nunique(dropna=False) for col in merged_df.columns]
})

unique_summary

                       Column  Unique Values
0                          ID          20000
1         ApplicationDate_ds1           2922
2                AnnualIncome          17516
3            EmploymentStatus              3
4              Experience_ds1             62
5                LoanDuration             10
6          NumberOfDependents              6
7         MonthlyDebtPayments           1299
8     NumberOfOpenCreditLines             14
9           BankruptcyHistory              2
10       PreviousLoanDefaults              2
11      LengthOfCreditHistory             29
12     CheckingAccountBalance           5151
13           TotalLiabilities          17163
14                   NetWorth          17724
15               LoanApproved              2
16        ApplicationDate_ds2          20000
17                        Age             63
18                CreditScore            322
19             EducationLevel              5
20             Experience_ds2             62
21                 LoanAmount          15578
22              MaritalStatus              5
23        HomeOwnershipStatus              4
24  CreditCardUtilizationRate           1962
25    NumberOfCreditInquiries              8
26                LoanPurpose              5
27             PaymentHistory             38
28      SavingsAccountBalance           9199
29                TotalAssets          18814
30                  JobTenure             17
31               InterestRate           2170
32                  RiskScore             53

In [27]:
for col in categorical_columns:
    print(f"{col}: {merged_df[col].unique()}")
    print("-" * 60)

ID: <StringArray>
[ 'A001',  'A002',  'A003',  'A004',  'A005',  'A006',  'A007',  'A008',
  'A009',  'A010',
 ...
 'B9992', 'B9993', 'B9994', 'B9995', 'B9996', 'B9997', 'B9998', 'B9999',
  'C001',  'C002']
Length: 20000, dtype: str
------------------------------------------------------------
ApplicationDate_ds1: <StringArray>
['01-01-2018', '02-01-2018', '03-01-2018', '04-01-2018', '05-01-2018',
 '06-01-2018', '07-01-2018', '08-01-2018', '09-01-2018', '10-01-2018',
 ...
 '22-12-2025', '23-12-2025', '24-12-2025', '25-12-2025', '26-12-2025',
 '27-12-2025', '28-12-2025', '29-12-2025', '30-12-2025', '31-12-2025']
Length: 2922, dtype: str
------------------------------------------------------------
EmploymentStatus: <StringArray>
['Employed', 'Self-Employed', 'Unemployed']
Length: 3, dtype: str
------------------------------------------------------------
ApplicationDate_ds2: <StringArray>
['01-01-2018', '02-01-2018', '03-01-2018', '04-01-2018', '05-01-2018',
 '06-01-2018', '07-01-2018', '08-01-2018', '09-01-2018', '10-01-2018',
 ...
 '24-09-2072', '25-09-2072', '26-09-2072', '27-09-2072', '28-09-2072',
 '29-09-2072', '30-09-2072', '01-10-2072', '02-10-2072', '03-10-2072']
Length: 20000, dtype: str
------------------------------------------------------------
EducationLevel: <StringArray>
['Master', 'Associate', 'Bachelor', 'High School', 'Doctorate']
Length: 5, dtype: str
------------------------------------------------------------
MaritalStatus: <StringArray>
['Married', 'Single', 'Divorced', 'Widowed', nan]
Length: 5, dtype: str
------------------------------------------------------------
HomeOwnershipStatus: <StringArray>
['Own', 'Mortgage', 'Rent', 'Other']
Length: 4, dtype: str
------------------------------------------------------------
LoanPurpose: <StringArray>
['Home', 'Debt Consolidation', 'Education', 'Other', 'Auto']
Length: 5, dtype: str
------------------------------------------------------------
RiskScore: <StringArray>
['49', 'XX', '54', '36', '44', '50', '42', '61', '53', '47', '56', '63', '58',
 '33', '39', '59', '48', '32', '51', '46', '60', '55', '62', '45', '37', '38',
 '57', '34', '64', '41', '40', '43', '28', '35', '66', '65', '70', '74', '67',
 '68', '73', '30', '79', '71', '69', '31', '72', '76', '84', '29', '75', '78',
 '77']
Length: 53, dtype: str
------------------------------------------------------------

In [28]:
merged_df.describe().T

,count,mean,std,min,25%,50%,75%,max
AnnualIncome,20000.0,59161.473550,40350.845168,15000.00,31679.00,48566.00,74391.00,485341.00
Experience_ds1,20000.0,17.522750,11.316836,0.00,9.00,17.00,25.00,61.00
LoanDuration,20000.0,54.057000,24.664857,12.00,36.00,48.00,72.00,120.00
NumberOfDependents,20000.0,1.517300,1.386325,0.00,0.00,1.00,2.00,5.00
MonthlyDebtPayments,20000.0,454.292700,240.507609,50.00,286.00,402.00,564.00,2919.00
NumberOfOpenCreditLines,20000.0,3.023350,1.736161,0.00,2.00,3.00,4.00,13.00
BankruptcyHistory,20000.0,0.052400,0.222838,0.00,0.00,0.00,0.00,1.00
PreviousLoanDefaults,20000.0,0.100050,0.300074,0.00,0.00,0.00,0.00,1.00
LengthOfCreditHistory,20000.0,14.957300,8.371552,1.00,8.00,15.00,22.00,29.00
CheckingAccountBalance,20000.0,1782.555100,2245.378812,24.00,551.00,1116.00,2126.00,52572.00
TotalLiabilities,20000.0,36252.412750,47251.510913,372.00,11196.75,22203.00,43146.50,1417302.00
NetWorth,20000.0,72294.318850,117920.021444,1000.00,8734.75,32855.50,88825.50,2603208.00
LoanApproved,20000.0,0.239000,0.426483,0.00,0.00,0.00,0.00,1.00
Age,20000.0,39.752600,11.622713,18.00,32.00,40.00,48.00,80.00
CreditScore,20000.0,571.612400,50.997358,343.00,540.00,578.00,609.00,712.00
Experience_ds2,19334.0,17.609651,11.500256,0.00,9.00,18.00,26.00,61.00
LoanAmount,20000.0,24882.867800,13427.421217,3674.00,15575.00,21914.50,30835.00,184732.00
CreditCardUtilizationRate,20000.0,37.776314,110.336244,1.00,4.10,11.30,25.60,992.00
NumberOfCreditInquiries,20000.0,0.993000,0.986965,0.00,0.00,1.00,2.00,7.00
PaymentHistory,20000.0,23.993650,4.945436,8.00,21.00,24.00,27.00,45.00
SavingsAccountBalance,20000.0,4946.052150,6604.887477,73.00,1541.75,2986.00,5873.25,200089.00
TotalAssets,20000.0,96964.395500,120799.939219,2098.00,31180.25,60699.00,117405.25,2619627.00
JobTenure,20000.0,5.002650,2.236804,0.00,3.00,5.00,6.00,16.00
InterestRate,20000.0,23.906040,4.220532,11.33,20.91,23.53,26.55,44.67

In [29]:
merged_df.describe(include=["object"]).T

C:\Users\MSI\AppData\Local\Temp\ipykernel_17476\395746782.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  merged_df.describe(include=["object"]).T

                     count unique         top   freq
ID                   20000  20000        A001      1
ApplicationDate_ds1  20000   2922  01-01-2018      7
EmploymentStatus     20000      3    Employed  17036
ApplicationDate_ds2  20000  20000  01-01-2018      1
EducationLevel       20000      5    Bachelor   6054
MaritalStatus        19985      4     Married  10029
HomeOwnershipStatus  20000      4    Mortgage   7939
LoanPurpose          20000      5        Home   5925
RiskScore            20000     53          XX   1275

In [30]:
missing_summary = pd.DataFrame({
    "Missing Count": merged_df.isnull().sum(),
    "Missing Percentage": (merged_df.isnull().sum() / len(merged_df)) * 100
})

missing_summary = missing_summary[
    missing_summary["Missing Count"] > 0
].sort_values("Missing Percentage", ascending=False)

missing_summary

                Missing Count  Missing Percentage
Experience_ds2            666               3.330
MaritalStatus              15               0.075

In [31]:
for col in categorical_columns:
    print(f"\n{col}")
    print(merged_df[col].value_counts(dropna=False).head(20))

ID
ID
A001    1
A002    1
A003    1
A004    1
A005    1
A006    1
A007    1
A008    1
A009    1
A010    1
A011    1
A012    1
A013    1
A014    1
A015    1
A016    1
A017    1
A018    1
A019    1
A020    1
Name: count, dtype: int64

ApplicationDate_ds1
ApplicationDate_ds1
01-01-2018    7
02-01-2018    7
03-01-2018    7
04-01-2018    7
05-01-2018    7
06-01-2018    7
07-01-2018    7
08-01-2018    7
09-01-2018    7
10-01-2018    7
11-01-2018    7
12-01-2018    7
13-01-2018    7
14-01-2018    7
15-01-2018    7
16-01-2018    7
17-01-2018    7
18-01-2018    7
19-01-2018    7
20-01-2018    7
Name: count, dtype: int64

EmploymentStatus
EmploymentStatus
Employed         17036
Self-Employed     1573
Unemployed        1391
Name: count, dtype: int64

ApplicationDate_ds2
ApplicationDate_ds2
01-01-2018    1
02-01-2018    1
03-01-2018    1
04-01-2018    1
05-01-2018    1
06-01-2018    1
07-01-2018    1
08-01-2018    1
09-01-2018    1
10-01-2018    1
11-01-2018    1
12-01-2018    1
13-01-2018    1
14-01-2018    1
15-01-2018    1
16-01-2018    1
17-01-2018    1
18-01-2018    1
19-01-2018    1
20-01-2018    1
Name: count, dtype: int64

EducationLevel
EducationLevel
Bachelor       6054
High School    5908
Associate      4034
Master         3050
Doctorate       954
Name: count, dtype: int64

MaritalStatus
MaritalStatus
Married     10029
Single       6077
Divorced     2881
Widowed       998
NaN            15
Name: count, dtype: int64

HomeOwnershipStatus
HomeOwnershipStatus
Mortgage    7939
Rent        6087
Own         3938
Other       2036
Name: count, dtype: int64

LoanPurpose
LoanPurpose
Home                  5925
Debt Consolidation    5027
Auto                  4034
Education             3008
Other                 2006
Name: count, dtype: int64

RiskScore
RiskScore
XX    1275
51    1271
53    1254
54    1226
55    1160
50    1095
56     912
49     890
57     826
40     799
48     748
58     719
59     622
36     547
47     527
60     474
44     473
39     426
46     420
38     382
Name: count, dtype: int64

In [32]:
[col for col in merged_df.columns if "risk" in col.lower()]

['RiskScore']

In [33]:
merged_df["RiskScore"].value_counts(dropna=False).head(20)

RiskScore
XX    1275
51    1271
53    1254
54    1226
55    1160
50    1095
56     912
49     890
57     826
40     799
48     748
58     719
59     622
36     547
47     527
60     474
44     473
39     426
46     420
38     382
Name: count, dtype: int64

In [34]:
risk_xx_count = (merged_df["RiskScore"] == "XX").sum()

print("Number of XX values:", risk_xx_count)
print("Percentage of XX values:", (risk_xx_count / len(merged_df)) * 100)

Number of XX values: 1275
Percentage of XX values: 6.375

In [35]:
merged_df.isnull()

,ID,ApplicationDate_ds1,AnnualIncome,EmploymentStatus,Experience_ds1,LoanDuration,NumberOfDependents,MonthlyDebtPayments,NumberOfOpenCreditLines,BankruptcyHistory,PreviousLoanDefaults,LengthOfCreditHistory,CheckingAccountBalance,TotalLiabilities,NetWorth,LoanApproved,ApplicationDate_ds2,Age,CreditScore,EducationLevel,Experience_ds2,LoanAmount,MaritalStatus,HomeOwnershipStatus,CreditCardUtilizationRate,NumberOfCreditInquiries,LoanPurpose,PaymentHistory,SavingsAccountBalance,TotalAssets,JobTenure,InterestRate,RiskScore
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [36]:
[col for col in merged_df.columns if "marital" in col.lower()]

['MaritalStatus']

In [37]:
merged_df["MaritalStatus"].value_counts(dropna=False)

MaritalStatus
Married     10029
Single       6077
Divorced     2881
Widowed       998
NaN            15
Name: count, dtype: int64

In [38]:
marital_missing = merged_df["MaritalStatus"].isnull().sum()

print("Missing MaritalStatus:", marital_missing)
print(
    "Missing percentage:",
    (marital_missing / len(merged_df)) * 100
)

Missing MaritalStatus: 15
Missing percentage: 0.075

In [39]:
[col for col in merged_df.columns if "experience" in col.lower()]

['Experience_ds1', 'Experience_ds2']

In [40]:
merged_df[["Experience_ds1", "Experience_ds2"]].isnull().sum()

Experience_ds1      0
Experience_ds2    666
dtype: int64

In [41]:
experience_comparison = merged_df[
    ["ID", "Experience_ds1", "Experience_ds2"]
].copy()

experience_comparison[
    experience_comparison["Experience_ds2"].isnull()
].head(10)

       ID  Experience_ds1  Experience_ds2
1    A002              15             NaN
66   A067              15             NaN
187  A188              15             NaN
219  A220              15             NaN
356  A357              15             NaN
408  A409              15             NaN
490  A491              15             NaN
497  A498              15             NaN
551  A552              15             NaN
573  A574              15             NaN

In [42]:
loan_counts = merged_df["LoanApproved"].value_counts().sort_index()
loan_percentages = (
    merged_df["LoanApproved"].value_counts(normalize=True)
    .sort_index() * 100
)

target_summary = pd.DataFrame({
    "Count": loan_counts,
    "Percentage": loan_percentages
})

target_summary

              Count  Percentage
LoanApproved
0             15220        76.1
1              4780        23.9

In [43]:
duplicate_rows = merged_df.duplicated().sum()

print("Number of duplicate rows:", duplicate_rows)

Number of duplicate rows: 0

In [44]:
duplicate_ids = merged_df["ID"].duplicated().sum()

print("Number of duplicate IDs:", duplicate_ids)

Number of duplicate IDs: 0